/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.lucassserver.com;

import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;

public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */

    private static final String DATABASE_URL = "jdbc:mysql://96.39.211.90:12345/serverdata";
    private static final String DATABASE_USER = "root";
    private static final String DATABASE_PASSWORD = "p757sbrq86xpd42jg655kb3";
    public LoginPage() {
        initComponents();
         loginbutton.addActionListener(e -> authenticateUser());

//        hide.addActionListener(e -> {
//            password.setEchoChar((char) 0); // Set the password field to display characters
//            hide.setVisible(false); // Hide the "hide" button
//            show.setVisible(true);  // Make the "show" button visible
//        });
//
//        // Add action listener to the "show" button
//        show.addActionListener(e -> {
//            password.setEchoChar('\u2022'); // Set the password field to hide characters
//            hide.setVisible(true);  // Make the "hide" button visible
//            show.setVisible(false); // Hide the "show" button
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        getHomepagePanel();
        getAdminPanel();
        getHelppagePanel();
        titleofpanel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        loginbutton = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleofpanel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titleofpanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleofpanel.setText("CTE Partners and Business Login Page");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleofpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleofpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Username");

        user.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user.setMinimumSize(new java.awt.Dimension(64, 36));
        user.setPreferredSize(new java.awt.Dimension(64, 36));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        loginbutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    private static JPanel helppage = null;

    public JPanel getHelppagePanel() {
        if (helppage == null) {
            helppage = new Helppage().getPanel();
        }
        return helppage;
    }



    private static JPanel homepage = null;

    public JPanel getHomepagePanel() {
        if (homepage == null) {
            homepage = new Homepage().getPanel();
        }
        return homepage;
    }

    private static JPanel adminpage = null;

    public JPanel getAdminPanel() {
        if (adminpage == null) {
            adminpage = new AdminPage().getMainPanel();
        }
        return adminpage;
    }

    private void authenticateUser() {
        String username = user.getText();
        String userPassword = new String(password.getPassword());

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection(DATABASE_URL, DATABASE_USER, DATABASE_PASSWORD);

            // Check if the user exists in the login table
            String loginQuery = "SELECT * FROM login WHERE username = ? AND password = ?";
            PreparedStatement loginStatement = connection.prepareStatement(loginQuery);
            loginStatement.setString(1, username);
            loginStatement.setString(2, userPassword);

            ResultSet loginResultSet = loginStatement.executeQuery();

            if (loginResultSet.next()) {
                // User exists in the login table
                String userType = loginResultSet.getString("usertype");

                // Check if the user is new
                String newUserQuery = "SELECT * FROM new_user WHERE nonnewuser = ?";
                PreparedStatement newUserStatement = connection.prepareStatement(newUserQuery);
                newUserStatement.setString(1, username);

                ResultSet newUserResultSet = newUserStatement.executeQuery();

                if (!newUserResultSet.next()) {
                    // User is new, add them to the new_user table
                    String insertNewUserQuery = "INSERT INTO new_user (nonnewuser) VALUES (?)";
                    PreparedStatement insertNewUserStmt = connection.prepareStatement(insertNewUserQuery);
                    insertNewUserStmt.setString(1, username);
                    insertNewUserStmt.executeUpdate();
                    insertNewUserStmt.close();

       //           JPanel HelpPanel = new Helppage().getPanel();
     //              jPanel2.add(HelpPanel, "HelpPanel");

   //                JPanel homePanel = new Homepage().getPanel();
 //                 jPanel2.add(homePanel, "homePanel");
//
//                    JPanel adminPanel = new AdminPage().getMainPanel();
 //                   jPanel2.add(adminPanel, "adminPanel");ni

                    // Now direct the new user to the HelpPanel
                    if ("normal".equals(userType)) {
                        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(jPanel2);
                        frame.setContentPane(helppage);
                        frame.revalidate();
                        frame.repaint();
                    }
                    if ("admin".equals(userType)) {
                        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(jPanel2);
                        frame.setContentPane(adminpage);
                        frame.revalidate();
                        frame.repaint();
                    }
                } else {
                    // User is not new, direct to home or admin panel based on user type
                    if ("normal".equals(userType)) {
                        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(jPanel2);
                        frame.setContentPane(homepage);
                        frame.revalidate();
                        frame.repaint();
                    } else if ("admin".equals(userType)) {
                        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(jPanel2);
                        frame.setContentPane(adminpage);
                        frame.revalidate();
                        frame.repaint();
                    } else {
                        dispose();
                        displayErrorMessage("<html><font color='red'>Invalid user type</font></html>");
                    }
                }

                newUserResultSet.close();
                newUserStatement.close();
            } else {
                // User does not exist in the login table
                displayErrorMessage("<html><font color='red'>Invalid username or password</font></html>");
            }

            loginResultSet.close();
            loginStatement.close();
            connection.close();

        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void displayErrorMessage(String errorMessage) {
        titleofpanel.setText(errorMessage);

        Timer timer = new Timer(2000, e -> titleofpanel.setText("CTE Partners and Business Login Page"));
        timer.setRepeats(false);
        timer.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton loginbutton;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel titleofpanel;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
